export const EMPTY_ACTION = "EMPTY_ACTION";
export const CHECK_USER_LOGGED_IN_REQUEST = "CHECK_USER_LOGGED_IN_REQUEST";
export const CHECK_USER_LOGGED_IN_SUCCESS = "CHECK_USER_LOGGED_IN_SUCCESS";
export const CHECK_USER_LOGGED_IN_FAILURE = "CHECK_USER_LOGGED_IN_FAILURE";
export const GOOGLE_OAUTH2_REQUEST = "GOOGLE_OAUTH2_REQUEST";
export const GOOGLE_OAUTH2_SUCCESS = "GOOGLE_OAUTH2_SUCCESS";
export const GOOGLE_OAUTH2_FAILURE = "GOOGLE_OAUTH2_FAILURE";