export const EMPTY_ACTION = "EMPTY_ACTION";
export const CHECK_USER_LOGGED_IN_REQUEST = "CHECK_USER_LOGGED_IN_REQUEST";
export const CHECK_USER_LOGGED_IN_SUCCESS = "CHECK_USER_LOGGED_IN_SUCCESS";
export const CHECK_USER_LOGGED_IN_FAILURE = "CHECK_USER_LOGGED_IN_FAILURE";